import { Poppins } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ['400'],
  subsets: ['latin']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
